### ISSUE TITLE
 user error (hGet': expected 4 bytes, got 0)

### ISSUE THREAD

**Issue by itsabhiraj01** [tweag/inline-js#27]
I was trying to use inline-js in my hakell project and while building it with `cabal v2-build` and ruuning it with `cabal v2-run` it got stuck at console without any output and while running the function with ghci I got this error:
```
<interactive>: user error (hGet': expected 4 bytes, got 0)
*** Exception: thread blocked indefinitely in an STM transaction
```

after setting the flag `nodeStdErrInherit` to `True` I got this error:
```
(node:21645) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:59
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/home/abhiraj/.cabal/share/x86_64-linux-ghc-8.6.5/inline-js-core-0.0.1/jsbits/eval.mjs' imported from /home/abhiraj/Projects/hk/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:149:40)
    at Loader.import (internal/modules/esm/loader.js:133:28)
    at internal/modules/cjs/loader.js:829:27
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I am using cabal.project file to download inline-js and inline-js-core.
this is my cabal.project file:
```
packages: .

source-repository-package
    type: git
    location: https://github.com/tweag/inline-js.git
    subdir: inline-js
    tag: fcd6c7821d7f7fafd614198db64ac887d593e6f7

source-repository-package
    type: git
    location: https://github.com/tweag/inline-js.git
    subdir: inline-js-core
    tag: fcd6c7821d7f7fafd614198db64ac887d593e6f7
```

This is the code I was trying to run: 
```
sumInJS :: Int -> Int -> IO Int
sumInJS v1 v2 =  withJSSession 
    defJSSessionOpts {nodeStdErrInherit = True}
        [expr| $v1 + $v2 |]
```

I was using node:v12.6.0, npm:v6.9.0 and ghc:8.6.5.

**Comment by itsabhiraj01** [comment]
After setting up a new project when I tried to install inline-js using stack I was able to run it. It seems like there is some issue while setting up inline-js with cabal.

**Comment by TerrorJack** [comment]
`inline-js` now has official `cabal` support and we test it on CI.
